sudo: required

services:
     - docker

before_install:
     - docker build -t prakashkharat/docker-react -f Dockerfile.dev .

script:
     - docker run -e CI=true prakashkharat/docker-react npm run test -- --coverage
